In [1]:
import pandas as pd

In [4]:
# Load a CSV file into a DataFrame
df = pd.read_csv('product_info.csv', delimiter=";")

# Display the first few rows
df.head()

,ref,itemDescriptionEN,brand,nameEN,encodeNameEN,title,description
0,000785FR,Combo Spot on 1 Pipette Dogs L 20-40 Kg,Frontline,Pet Care,health-care/veterinary-products,Combo Spot on Pipette Dogs 20-40 Kg,"The simple itching, caused by fleas can be a..."
1,000946DK,Men Eau de Toilette,DKNY,Fragrances,men/perfumes/fragrances,Men Eau de Toilette,"Discover DKNY Men Eau de Toilette — a modern, ..."
2,023444DK,Be Delicious Fresh Blossom Body Mist,DKNY,Fragrances,fragrance/women,Be Delicious Fresh Blossom Body Mist,DKNY Be Delicious Fresh Blossom Body Mist is a...
3,000784FR,Combo Spot on 1 Pipette Dogs M 10-20 Kg,Frontline,Pet Care,health-care/veterinary-products,Spot-On 10-20 Kg,"Have a dog as a companion is great, even bette..."
4,025034DK,Be Delicious Ice Pop Citrus Splash Eau de Parfum,DKNY,Fragrances,fragrance/women,Be Delicious Ice Pop Citrus Splash Eau de Parfum,DKNY Be Delicious Ice Pop Citrus Splash Eau de...

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15990 entries, 0 to 15989
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ref                15990 non-null  object
 1   itemDescriptionEN  15989 non-null  object
 2   brand              15989 non-null  object
 3   nameEN             15988 non-null  object
 4   encodeNameEN       15988 non-null  object
 5   title              15988 non-null  object
 6   description        15986 non-null  object
dtypes: object(7)
memory usage: 874.6+ KB

In [10]:
print(df['encodeNameEN'].value_counts().to_string())

encodeNameEN
fragrance/women                                            852
men/perfumes/fragrances                                    400
skin/dehydration/specific-moisturizers                     399
skin/cleansers-tonners/combination-to-oily-skin            338
skin/cleansers-tonners/normal-skin                         330
skin/global-anti-aging/specific-moisturizers               323
body/moisturisers/dryness-dehydration                      263
skin/dark-spots/seruns                                     261
skin/masks-exfoliators/tissue-masks                        261
body/bath-shower/dryness-dehydration                       242
hair/styling                                               235
skin/global-anti-aging/seruns                              221
health-care/nutrition                                      209
body/hands                                                 180
skin/moisturisers/oiliness-acne-pores                      177
skin/dehydration/seruns                                    173
skin/dark-spots/specific-moisturizers                      172
skin/cleansers-tonners/sensitive-skin                      169
skin/essences-preparing-lotions                            160
skin/eye-care/global-anti-aging                            159
mom-baby/first-years/hygiene-moisturization                156
sun-tan/face/normal-skin                                   153
skin/masks-exfoliators/exfoliating                         147
skin/loss-firmness/specific-moisturizers                   147
makeup/eyes-brows/mascara                                  138
skin/cleansers-tonners/dry-skin                            130
body/feet                                                  129
sun-tan/body/normal-skin                                   126
skin/lip-care/dryness-dehydration                          115
health-care/oral-health/toothbrushes-accessories           113
makeup/complexion/accessories-brushes                      111
health-care/veterinary-products                            111
skin/loss-firmness/seruns                                  109
mom-baby/first-years/feeding-accessories                   109
skin/oiliness-acne-pores/seruns                            108
skin/moisturisers/sensitive-intolerant-skin                105
hair/normal-hair/shampoo                                   103
body/female-intimate-hygiene                               102
body/sexuality                                             100
hair/dry-damaged-hair/shampoo                               99
makeup/eyes-brows/eyeliners-pencil                          99
fragrance/fragranced-moisturizers                           98
makeup/complexion/makeup-removers                           94
skin/masks-exfoliators/moisturizing-masks                   94
makeup/eyes-brows/eye-shadow                                91
sun-tan/self-tanning                                        91
makeup/complexion/foundation                                90
men/hair/styling                                            90
body/deodorants                                             90
hair/dry-damaged-hair/seruns-leave-in                       89
hair/hair-mask/dry-to-very-dry-hair                         88
makeup/complexion/concealers-highlighters                   87
skin/first-signs-age/specific-moisturizers                  85
makeup/eyes-brows/accessories-brushes                       85
sun-tan/face/combination-to-oily-skin                       79
skin/dark-spots/eye-contour                                 78
makeup/complexion/primers                                   77
skin/eye-care/dryness-dehydration                           77
hair/colour/shampoo                                         77
skin/moisturisers/redness-rosacea                           76
skin/masks-exfoliators/purifying-masks                      75
skin/beauty-tech                                            74
skin/deep-wrinkles/specific-moisturizers                    74
makeup/lips/lipstick                                        71
health-care/contact-lenses                                  71
body/exfoliators                                            70
makeup/eyes-brows/eyebrows                                  68
hair/hair-loss/seruns-leave-in                              68
hair/contitioner/dry-to-very-dry-hair                       68
hair/brushes-combs                                          67
supplements-vitamins/weight-management                      67
makeup/lips/lipgloss                                        65
makeup/complexion/powders                                   65
supplements-vitamins/energy-tiredness                       65
sun-tan/after-sun                                           64
health-care/tights-orthoses                                 64
fragrance/bath                                              64
skin/first-signs-age/seruns                                 63
sun-tan/face/lightness-anti-spots                           62
supplements-vitamins/anti-ageing                            60
makeup/complexion/bb-creams-cc-creams                       60
hair/curly-hair/seruns-leave-in                             59
mom-baby/after-birth/breast-pumps                           59
sun-tan/face/sensitive-intolerant-skin                      58
makeup/lips/lipbalm                                         58
hair/contitioner/normal-hair                                58
hair/accessories                                            58
health-care/oral-health/toothpaste                          58
skin/deep-wrinkles/seruns                                   55
skin/makeup-removers                                        54
mom-baby/sun-protection                                     54
hair/damaged-hair/masks                                     54
skin/eye-care/lost-firmness                                 53
men/perfumes/deodorants                                     53
skin/eye-care/first-wrinkles                                53
health-care/oral-health/specific-care                       53
skin/seruns/redness-rosacea                                 53
hair/colour/conditioners                                    52
hair/normal-hair/seruns-leave-in                            51
hair/anti-dandruff/shampoo                                  51
hair/shampoo/oily-hair                                      49
skin/oiliness-acne-pores/targeted-correction                49
men/body/deodorants-antiperspirants                         49
body/firming-care                                           48
health-care/nasal-congestion                                48
men/shaving/shaving                                         48
health-care/first-aid                                       48
skin/masks-exfoliators/anti-ageing                          47
hair/hair-loss/shampoo                                      46
hair/damaged-hair/seruns-leave-in                           46
men/shaving/after-shave                                     45
makeup/complexion/blush                                     45
supplements-vitamins/digestive-health                       44
hair/shampoo/volume                                         43
skin/facial-oils                                            43
hair/shampoo/sensitive-scalp                                42
body/scars-reparing-creams                                  42
hair/seruns-leave-in                                        41
makeup/nails/accessories-tools                              41
skin/cleansers-tonners                                      41
makeup/eyes-brows/eye-makeup-removers                       40
hair/damaged-hair/shampoo                                   40
men/body/hygiene-exfoliation                                40
skin/masks-exfoliators/anti-spots-masks                     40
health-care/oral-health/mouthwashes                         39
skin/deep-wrinkles/eye-contour                              39
makeup/nails/top-basecoats                                  39
makeup/complexion/bronzer                                   38
hair/damaged-hair/conditioners                              37
supplements-vitamins/hair-care                              37
health-care/dressings-anti-bedsore                          37
supplements-vitamins/vitamins-minerals                      36
supplements-vitamins/sleep-anxiety                          35
hair/colour/masks                                           35
body/atopic-dermatitis/bath-shower                          34
fragrance/deodorants                                        33
mom-baby/after-birth/breast-feeding                         33
skin/targeted-correction/oiliness-acne-pores                32
body/moisturisers/atopic-dermatitis                         32
men/shaving/styling                                         31
body/sculping                                               30
health-care/diapers-incontinence                            30
sun-tan/eyes-lips-sensitive-areas                           29
makeup/lips/lipliners                                       29
hair/preshampoo-head-scrub                                  29
supplements-vitamins/bones-joints                           29
men/perfumes/after-shave                                    28
mom-baby/first-years/diaper-change                          28
men/sexuality/comdoms-lubricants                            28
men/skin/cleansers-tonners                                  27
hair/colour/color-protector                                 26
sun-tan/dark-spots                                          26
hair/colour/hair-dye                                        26
hair/shampoo-dry                                            26
hair/hair-mask/normal-hair                                  25
hair/seruns-leave-in/volume                                 25
hair/contitioner/volume                                     25
makeup/complexion/compact-foundation                        25
health-care/bones-joints                                    24
health-care/insect-repellent                                24
supplements-vitamins/brain-memory                           24
body/stretch-marks                                          23
skin/eyebrows-eyelashes                                     23
makeup/nails/nail-polish                                    23
sun-tan/body/sensitive-intolerant-skin                      22
health-care/tensiometers                                    22
makeup/nails/treatments                                     22
mom-baby/first-years/fragrances                             22
hair/contitioner                                            22
body/atopic-dermatitis/specific-care                        22
sun-tan/face/dry-skin                                       22
hair/seruns-leave-in/sensitive-scalp                        22
skin/lip-care/wrinkles-fillers                              21
men/skin/anti-ageing                                        21
skin/neck-decollete-care                                    20
sun-tan/sensitivity/face                                    20
sun-tan/normal-skin/body                                    20
health-care/scars-reparing-creams                           19
health-care/earplugs                                        19
body/water-retention                                        19
hair/curly-hair/shampoo                                     19
supplements-vitamins/heart-circulation                      19
men/sexuality/accessories                                   19
mom-baby/first-years/atopic-skin                            18
health-care/oral-health/deep-cleansing                      18
mom-baby/maternity-essentials/maternity-bag                 18
men/skin/moisturisers/oily-skin                             18
hair/sun-care                                               18
hair/anti-ageing/shampoo                                    17
hair/contitioner/hair-loss                                  16
men/hair/hair-loss                                          16
body/cellulite-control                                      16
skin/eye-care/sensitive-intolerant-skin                     16
skin/dark-spots/essences-preparing-lotions                  16
hair/curly-hair/conditioners                                16
supplements-vitamins/bodybuilding                           16
skin/global-anti-aging/essences-preparing-lotions           15
men/hair/shampoos/normal-hair                               15
body/moisturisers                                           15
mom-baby/first-years/soothers                               15
hair/curly-hair/masks                                       15
skin/oiliness-acne-pores/masks-exfoliators                  15
men/perfumes/bath                                           15
mom-baby/first-years/nasal-congestion                       15
supplements-vitamins/menopause                              14
health-care/medication-boxes                                14
mom-baby/after-birth/bras                                   14
sun-tan/normal-skin/face                                    14
hair/supplements                                            14
body/bust-care                                              14
mom-baby/first-years/first-teeth                            14
hair/shampoo                                                14
body/stubborn-fat                                           13
mom-baby/first-years                                        13
skin/oiliness-acne-pores/essences-preparing-lotions         13
hair/seruns-leave-in/straightening                          12
mom-baby/maternity-essentials/strollers-accessories         12
men/skin/moisturisers/dry-skin                              12
skin/dehydration/essences-preparing-lotions                 11
hair/anti-ageing/conditioners                               11
hair/anti-ageing/seruns-leave-in                            11
men/body/moisturization-toning                              11
mom-baby/before-birth/stretch-marks-firmness                11
sun-tan/supplements                                         11
skin/dark-spots/targeted-correction                         11
supplements-vitamins/sun-care                               11
mom-baby/first-years/lices                                  11
gifting/for-her                                             10
skin/seruns                                                 10
health-care/anti-fungals                                    10
hair/hair-loss/food-suplements                              10
men/skin/seruns                                              9
body/bath-shower                                             9
men/hair/shampoos                                            9
makeup/nails/nail-polish-remover                             8
hair/anti-ageing/masks                                       8
hair/hair-loss/masks                                         8
sun-tan/hair                                                 8
sun-tan/pre-sun                                              8
sun-tan/body                                                 8
men/hair/normal-hair                                         8
hair/frizz-unruly-hair/seruns-leave-in                       8
health-care/nebulizers                                       8
men/skin/eye-care/dark-circles-puffiness                     8
supplements-vitamins/urinary-concerns                        8
hair/curly-hair                                              8
mom-baby/first-years/diapers                                 7
mom-baby/maternity-essentials/thermometers                   7
men/hair/shampoos/hair-loss                                  7
hair/hair-mask                                               7
skin/targeted-correction/lightness-anti-spots                7
skin/sensitive-intolerant-skin/cleansers-tonners             7
skin/global-anti-aging                                       7
sun-tan/oily-combination-skin                                7
hair/colour                                                  7
body/moisturisers/seborrheic-dermatitis                      7
hair/hair-mask/volume                                        7
men/skin/deep-wrinkles-loss-firmness                         7
body/moisturisers/psoriasis                                  7
men/shaving/accessories                                      6
skin/loss-firmness/essences-preparing-lotions                6
supplements-vitamins/nutrition                               6
health-care/menopause                                        6
hair/hair-mask/oily-hair                                     6
supplements-vitamins/fertility                               6
fragrance                                                    6
hair/volume                                                  6
body/bath-shower/seborrheic-dermatitis                       6
body/beauty-tech                                             6
sun-tan/sensitivity/body                                     6
skin/moisturisers                                            5
body/firmin-care                                             5
men/skin/first-signs-age                                     5
hair/shampoo/straightening                                   5
men/supplements/bodybuilding                                 5
hair/hair-loss                                               5
skin/masks-exfoliators                                       5
health-care/diabetics                                        5
men/supplements/multivitamins                                5
hair/sensitive-scalp                                         5
mom-baby/first-years/cramps                                  5
mom-baby/first-years/cradle-cap                              5
men/skin/moisturisers/sensitive-skin                         5
body/psoriasis/specific-care                                 5
hair/anti-dandruff/seruns-leave-in                           5
health-care/psoriasis/bath-shower                            4
men/skin/acne                                                4
hair/frizz-unruly-hair/shampoo                               4
gifting                                                      4
men/skin/eye-care/wrinkles                                   4
hair/hair-mask/straightening                                 4
sun-tan/body/dry-skin                                        4
body/hairs-removal                                           4
men/supplements/fertility                                    4
sun-tan/dry-skin/face                                        4
health-care/sleep-anxiety                                    4
hair/frizz-unruly-hair/conditioners                          4
hair/sensitive-scalp/preshampoo-head-scrub                   4
body/bath-shower/psoriasis                                   4
health-care/seborrheic-dermatitis/specific-care              4
supplements-vitamins/eye-care                                4
mom-baby/before-birth/support-briefs-belts                   3
men/sexuality/food-supplements                               3
hair/contitioner/oily-hair                                   3
skin/hairs-removal                                           3
skin/targeted-correction/deep-whrinkles                      3
hair/dry-damaged-hair/styling                                3
hair/damaged-hair/preshampoo-head-scrub                      3
men/skin/moisturisers                                        3
health-care/atopic-dermatitis/specific-care                  3
skin/redness/masks-exfoliators                               3
hair/frizz-unruly-hair/masks                                 3
supplements-vitamins/sexuality                               3
skin/eye-care                                                3
hair/damaged-hair                                            3
hair/oily-hair/preshampoo-head-scrub                         3
men/supplements/hair                                         3

In [12]:
# Define the unwanted categories
unwanted_categories = [
    'christmas/gift-sets',
    'gifting/perfumes',
    'christmas/gifts-premium',
    'gifting/premium',
    'gifting/secret-santa',
    'brands?d=3',
    'gifting',
    'gifting/for-her'
]

# Remove rows where 'encodeNameEN' matches any in the list
df_cleaned = df[~df['encodeNameEN'].isin(unwanted_categories)]

In [13]:
df_cleaned

,ref,itemDescriptionEN,brand,nameEN,encodeNameEN,title,description
0,000785FR,Combo Spot on 1 Pipette Dogs L 20-40 Kg,Frontline,Pet Care,health-care/veterinary-products,Combo Spot on Pipette Dogs 20-40 Kg,"The simple itching, caused by fleas can be a..."
1,000946DK,Men Eau de Toilette,DKNY,Fragrances,men/perfumes/fragrances,Men Eau de Toilette,"Discover DKNY Men Eau de Toilette — a modern, ..."
2,023444DK,Be Delicious Fresh Blossom Body Mist,DKNY,Fragrances,fragrance/women,Be Delicious Fresh Blossom Body Mist,DKNY Be Delicious Fresh Blossom Body Mist is a...
3,000784FR,Combo Spot on 1 Pipette Dogs M 10-20 Kg,Frontline,Pet Care,health-care/veterinary-products,Spot-On 10-20 Kg,"Have a dog as a companion is great, even bette..."
4,025034DK,Be Delicious Ice Pop Citrus Splash Eau de Parfum,DKNY,Fragrances,fragrance/women,Be Delicious Ice Pop Citrus Splash Eau de Parfum,DKNY Be Delicious Ice Pop Citrus Splash Eau de...
...,...,...,...,...,...,...,...
15985,025004G0,BB Cream 4-in-1 Treatment,Gamarde,BB Creams & CC Creams,makeup/complexion/bb-creams-cc-creams,BB Cream 4-in-1 Tinted Treatment,Discover Gamarde BB Cream 4-in-1 Tinted Treatm...
15986,024555UF,Curcuma Plus Food Supplement,Vitafor,Nutrition & Food Supplements,health-care/nutrition,Curcuma Plus Food Supplement Capsules,Boost immunity and fight oxidative stress with...
15987,024558UF,Endurance Caffeine Gel Food Supplement,Vitafor,Nutrition & Food Supplements,health-care/nutrition,Endurance Caffeine Gel Carbohydrate Food Suppl...,Vitafor Endurance Caffeine Gel Carbohydrate Fo...
15988,024571UF,Lipix 6 Safflower and Grape Seed Oil Food Supp...,Vitafor,Nutrition & Food Supplements,health-care/nutrition,Lipix 6 Safflower and Grape Seed Oil Food Supp...,Boost workouts and metabolism with Vitafor Lip...
15989,024837B6,Shine Brown Chocolate Quick Tanning Cream,Byrokko,Self-Tanning,sun-tan/self-tanning,Shine Brown Chocolate Quick Tanning Cream for ...,"Achieve an intense, deep chocolate tan with By..."

In [15]:
print(df_cleaned['encodeNameEN'].value_counts().to_string())

encodeNameEN
fragrance/women                                            852
men/perfumes/fragrances                                    400
skin/dehydration/specific-moisturizers                     399
skin/cleansers-tonners/combination-to-oily-skin            338
skin/cleansers-tonners/normal-skin                         330
skin/global-anti-aging/specific-moisturizers               323
body/moisturisers/dryness-dehydration                      263
skin/masks-exfoliators/tissue-masks                        261
skin/dark-spots/seruns                                     261
body/bath-shower/dryness-dehydration                       242
hair/styling                                               235
skin/global-anti-aging/seruns                              221
health-care/nutrition                                      209
body/hands                                                 180
skin/moisturisers/oiliness-acne-pores                      177
skin/dehydration/seruns                                    173
skin/dark-spots/specific-moisturizers                      172
skin/cleansers-tonners/sensitive-skin                      169
skin/essences-preparing-lotions                            160
skin/eye-care/global-anti-aging                            159
mom-baby/first-years/hygiene-moisturization                156
sun-tan/face/normal-skin                                   153
skin/masks-exfoliators/exfoliating                         147
skin/loss-firmness/specific-moisturizers                   147
makeup/eyes-brows/mascara                                  138
skin/cleansers-tonners/dry-skin                            130
body/feet                                                  129
sun-tan/body/normal-skin                                   126
skin/lip-care/dryness-dehydration                          115
health-care/oral-health/toothbrushes-accessories           113
makeup/complexion/accessories-brushes                      111
health-care/veterinary-products                            111
skin/loss-firmness/seruns                                  109
mom-baby/first-years/feeding-accessories                   109
skin/oiliness-acne-pores/seruns                            108
skin/moisturisers/sensitive-intolerant-skin                105
hair/normal-hair/shampoo                                   103
body/female-intimate-hygiene                               102
body/sexuality                                             100
makeup/eyes-brows/eyeliners-pencil                          99
hair/dry-damaged-hair/shampoo                               99
fragrance/fragranced-moisturizers                           98
makeup/complexion/makeup-removers                           94
skin/masks-exfoliators/moisturizing-masks                   94
makeup/eyes-brows/eye-shadow                                91
sun-tan/self-tanning                                        91
men/hair/styling                                            90
makeup/complexion/foundation                                90
body/deodorants                                             90
hair/dry-damaged-hair/seruns-leave-in                       89
hair/hair-mask/dry-to-very-dry-hair                         88
makeup/complexion/concealers-highlighters                   87
makeup/eyes-brows/accessories-brushes                       85
skin/first-signs-age/specific-moisturizers                  85
sun-tan/face/combination-to-oily-skin                       79
skin/dark-spots/eye-contour                                 78
hair/colour/shampoo                                         77
makeup/complexion/primers                                   77
skin/eye-care/dryness-dehydration                           77
skin/moisturisers/redness-rosacea                           76
skin/masks-exfoliators/purifying-masks                      75
skin/beauty-tech                                            74
skin/deep-wrinkles/specific-moisturizers                    74
health-care/contact-lenses                                  71
makeup/lips/lipstick                                        71
body/exfoliators                                            70
makeup/eyes-brows/eyebrows                                  68
hair/contitioner/dry-to-very-dry-hair                       68
hair/hair-loss/seruns-leave-in                              68
supplements-vitamins/weight-management                      67
hair/brushes-combs                                          67
makeup/lips/lipgloss                                        65
supplements-vitamins/energy-tiredness                       65
makeup/complexion/powders                                   65
fragrance/bath                                              64
sun-tan/after-sun                                           64
health-care/tights-orthoses                                 64
skin/first-signs-age/seruns                                 63
sun-tan/face/lightness-anti-spots                           62
makeup/complexion/bb-creams-cc-creams                       60
supplements-vitamins/anti-ageing                            60
mom-baby/after-birth/breast-pumps                           59
hair/curly-hair/seruns-leave-in                             59
hair/accessories                                            58
hair/contitioner/normal-hair                                58
makeup/lips/lipbalm                                         58
sun-tan/face/sensitive-intolerant-skin                      58
health-care/oral-health/toothpaste                          58
skin/deep-wrinkles/seruns                                   55
mom-baby/sun-protection                                     54
skin/makeup-removers                                        54
hair/damaged-hair/masks                                     54
skin/eye-care/lost-firmness                                 53
skin/eye-care/first-wrinkles                                53
skin/seruns/redness-rosacea                                 53
health-care/oral-health/specific-care                       53
men/perfumes/deodorants                                     53
hair/colour/conditioners                                    52
hair/anti-dandruff/shampoo                                  51
hair/normal-hair/seruns-leave-in                            51
hair/shampoo/oily-hair                                      49
men/body/deodorants-antiperspirants                         49
skin/oiliness-acne-pores/targeted-correction                49
body/firming-care                                           48
health-care/first-aid                                       48
health-care/nasal-congestion                                48
men/shaving/shaving                                         48
skin/masks-exfoliators/anti-ageing                          47
hair/hair-loss/shampoo                                      46
hair/damaged-hair/seruns-leave-in                           46
men/shaving/after-shave                                     45
makeup/complexion/blush                                     45
supplements-vitamins/digestive-health                       44
hair/shampoo/volume                                         43
skin/facial-oils                                            43
body/scars-reparing-creams                                  42
hair/shampoo/sensitive-scalp                                42
makeup/nails/accessories-tools                              41
hair/seruns-leave-in                                        41
skin/cleansers-tonners                                      41
skin/masks-exfoliators/anti-spots-masks                     40
hair/damaged-hair/shampoo                                   40
men/body/hygiene-exfoliation                                40
makeup/eyes-brows/eye-makeup-removers                       40
skin/deep-wrinkles/eye-contour                              39
health-care/oral-health/mouthwashes                         39
makeup/nails/top-basecoats                                  39
makeup/complexion/bronzer                                   38
hair/damaged-hair/conditioners                              37
supplements-vitamins/hair-care                              37
health-care/dressings-anti-bedsore                          37
supplements-vitamins/vitamins-minerals                      36
hair/colour/masks                                           35
supplements-vitamins/sleep-anxiety                          35
body/atopic-dermatitis/bath-shower                          34
fragrance/deodorants                                        33
mom-baby/after-birth/breast-feeding                         33
skin/targeted-correction/oiliness-acne-pores                32
body/moisturisers/atopic-dermatitis                         32
men/shaving/styling                                         31
body/sculping                                               30
health-care/diapers-incontinence                            30
hair/preshampoo-head-scrub                                  29
makeup/lips/lipliners                                       29
supplements-vitamins/bones-joints                           29
sun-tan/eyes-lips-sensitive-areas                           29
men/sexuality/comdoms-lubricants                            28
men/perfumes/after-shave                                    28
mom-baby/first-years/diaper-change                          28
men/skin/cleansers-tonners                                  27
hair/shampoo-dry                                            26
hair/colour/color-protector                                 26
sun-tan/dark-spots                                          26
hair/colour/hair-dye                                        26
makeup/complexion/compact-foundation                        25
hair/contitioner/volume                                     25
hair/seruns-leave-in/volume                                 25
hair/hair-mask/normal-hair                                  25
supplements-vitamins/brain-memory                           24
health-care/bones-joints                                    24
health-care/insect-repellent                                24
makeup/nails/nail-polish                                    23
body/stretch-marks                                          23
skin/eyebrows-eyelashes                                     23
hair/seruns-leave-in/sensitive-scalp                        22
body/atopic-dermatitis/specific-care                        22
makeup/nails/treatments                                     22
hair/contitioner                                            22
mom-baby/first-years/fragrances                             22
sun-tan/face/dry-skin                                       22
sun-tan/body/sensitive-intolerant-skin                      22
health-care/tensiometers                                    22
skin/lip-care/wrinkles-fillers                              21
men/skin/anti-ageing                                        21
sun-tan/normal-skin/body                                    20
sun-tan/sensitivity/face                                    20
skin/neck-decollete-care                                    20
health-care/earplugs                                        19
hair/curly-hair/shampoo                                     19
health-care/scars-reparing-creams                           19
men/sexuality/accessories                                   19
supplements-vitamins/heart-circulation                      19
body/water-retention                                        19
mom-baby/maternity-essentials/maternity-bag                 18
mom-baby/first-years/atopic-skin                            18
men/skin/moisturisers/oily-skin                             18
hair/sun-care                                               18
health-care/oral-health/deep-cleansing                      18
hair/anti-ageing/shampoo                                    17
skin/dark-spots/essences-preparing-lotions                  16
men/hair/hair-loss                                          16
skin/eye-care/sensitive-intolerant-skin                     16
hair/curly-hair/conditioners                                16
body/cellulite-control                                      16
hair/contitioner/hair-loss                                  16
supplements-vitamins/bodybuilding                           16
men/hair/shampoos/normal-hair                               15
hair/curly-hair/masks                                       15
body/moisturisers                                           15
skin/global-anti-aging/essences-preparing-lotions           15
men/perfumes/bath                                           15
mom-baby/first-years/nasal-congestion                       15
mom-baby/first-years/soothers                               15
skin/oiliness-acne-pores/masks-exfoliators                  15
health-care/medication-boxes                                14
mom-baby/first-years/first-teeth                            14
mom-baby/after-birth/bras                                   14
supplements-vitamins/menopause                              14
hair/supplements                                            14
body/bust-care                                              14
sun-tan/normal-skin/face                                    14
hair/shampoo                                                14
skin/oiliness-acne-pores/essences-preparing-lotions         13
mom-baby/first-years                                        13
body/stubborn-fat                                           13
hair/seruns-leave-in/straightening                          12
men/skin/moisturisers/dry-skin                              12
mom-baby/maternity-essentials/strollers-accessories         12
mom-baby/before-birth/stretch-marks-firmness                11
men/body/moisturization-toning                              11
skin/dehydration/essences-preparing-lotions                 11
hair/anti-ageing/conditioners                               11
mom-baby/first-years/lices                                  11
hair/anti-ageing/seruns-leave-in                            11
supplements-vitamins/sun-care                               11
skin/dark-spots/targeted-correction                         11
sun-tan/supplements                                         11
skin/seruns                                                 10
hair/hair-loss/food-suplements                              10
health-care/anti-fungals                                    10
men/skin/seruns                                              9
men/hair/shampoos                                            9
body/bath-shower                                             9
sun-tan/hair                                                 8
men/skin/eye-care/dark-circles-puffiness                     8
hair/hair-loss/masks                                         8
supplements-vitamins/urinary-concerns                        8
sun-tan/pre-sun                                              8
hair/curly-hair                                              8
sun-tan/body                                                 8
men/hair/normal-hair                                         8
hair/anti-ageing/masks                                       8
hair/frizz-unruly-hair/seruns-leave-in                       8
health-care/nebulizers                                       8
makeup/nails/nail-polish-remover                             8
hair/colour                                                  7
men/skin/deep-wrinkles-loss-firmness                         7
body/moisturisers/psoriasis                                  7
skin/sensitive-intolerant-skin/cleansers-tonners             7
mom-baby/first-years/diapers                                 7
men/hair/shampoos/hair-loss                                  7
hair/hair-mask                                               7
skin/global-anti-aging                                       7
mom-baby/maternity-essentials/thermometers                   7
body/moisturisers/seborrheic-dermatitis                      7
hair/hair-mask/volume                                        7
sun-tan/oily-combination-skin                                7
skin/targeted-correction/lightness-anti-spots                7
supplements-vitamins/fertility                               6
men/shaving/accessories                                      6
health-care/menopause                                        6
skin/loss-firmness/essences-preparing-lotions                6
fragrance                                                    6
supplements-vitamins/nutrition                               6
hair/hair-mask/oily-hair                                     6
body/beauty-tech                                             6
hair/volume                                                  6
body/bath-shower/seborrheic-dermatitis                       6
sun-tan/sensitivity/body                                     6
mom-baby/first-years/cramps                                  5
hair/anti-dandruff/seruns-leave-in                           5
hair/sensitive-scalp                                         5
men/supplements/multivitamins                                5
men/skin/first-signs-age                                     5
men/skin/moisturisers/sensitive-skin                         5
skin/masks-exfoliators                                       5
health-care/diabetics                                        5
body/firmin-care                                             5
men/supplements/bodybuilding                                 5
body/psoriasis/specific-care                                 5
hair/hair-loss                                               5
mom-baby/first-years/cradle-cap                              5
hair/shampoo/straightening                                   5
skin/moisturisers                                            5
health-care/sleep-anxiety                                    4
men/skin/acne                                                4
hair/sensitive-scalp/preshampoo-head-scrub                   4
health-care/seborrheic-dermatitis/specific-care              4
men/supplements/fertility                                    4
hair/frizz-unruly-hair/shampoo                               4
men/skin/eye-care/wrinkles                                   4
body/bath-shower/psoriasis                                   4
sun-tan/dry-skin/face                                        4
hair/hair-mask/straightening                                 4
supplements-vitamins/eye-care                                4
body/hairs-removal                                           4
health-care/psoriasis/bath-shower                            4
hair/frizz-unruly-hair/conditioners                          4
sun-tan/body/dry-skin                                        4
skin/redness/masks-exfoliators                               3
skin/targeted-correction/deep-whrinkles                      3
hair/oily-hair/preshampoo-head-scrub                         3
supplements-vitamins/sexuality                               3
hair/contitioner/oily-hair                                   3
men/supplements/hair                                         3
men/skin/moisturisers                                        3
skin/hairs-removal                                           3
hair/dry-damaged-hair/styling                                3
mom-baby/before-birth/support-briefs-belts                   3
hair/damaged-hair/preshampoo-head-scrub                      3
hair/damaged-hair                                            3
hair/frizz-unruly-hair/masks                                 3
men/sexuality/food-supplements                               3
skin/eye-care                                                3
health-care/atopic-dermatitis/specific-care                  3
skin/deep-wrinkles/targeted-correction                       2
men/skin/beard-folliculitis                                  2

In [17]:
# Load a CSV file into a DataFrame
df_cat = pd.read_csv('product_description.csv', delimiter=";")

# Display the first few rows
df_cat.head()

                           encodeNameEN
0    body/atopic-dermatitis/bath-shower
1  body/atopic-dermatitis/specific-care
2                      body/bath-shower
3  body/bath-shower/dryness-dehydration
4            body/bath-shower/psoriasis

In [19]:
# Clean column names just to be sure
df_cleaned.columns = df_cleaned.columns.str.strip()
df_cat.columns = df_cat.columns.str.strip()

# Get unique categories from both DataFrames
cleaned_categories = set(df_cleaned['encodeNameEN'].dropna().unique())
cat_categories = set(df_cat['encodeNameEN'].dropna().unique())

# Find categories in df_cleaned but not in df_cat
missing_in_cat = cleaned_categories - cat_categories

# Filter out non-strings before sorting
missing_in_cat = [cat for cat in missing_in_cat if isinstance(cat, str)]

# Display result
print("Categories in df_cleaned but NOT in df_cat:")
for category in sorted(missing_in_cat):
    print(category)

print(f"\nTotal unmatched categories: {len(missing_in_cat)}")

Categories in df_cleaned but NOT in df_cat:
body/moisturisers/dryness-dehydration

Total unmatched categories: 1

In [23]:
df_cleaned = df_cleaned.copy()

df_cleaned['encodeNameEN'] = df_cleaned['encodeNameEN'].replace(
    'body/moisturisers/dryness-dehydration', 
    'body/dehydration/moisturizers'
)

In [24]:
print(df_cleaned['encodeNameEN'].value_counts().to_string())

encodeNameEN
fragrance/women                                            852
men/perfumes/fragrances                                    400
skin/dehydration/specific-moisturizers                     399
skin/cleansers-tonners/combination-to-oily-skin            338
skin/cleansers-tonners/normal-skin                         330
skin/global-anti-aging/specific-moisturizers               323
body/dehydration/moisturizers                              263
skin/masks-exfoliators/tissue-masks                        261
skin/dark-spots/seruns                                     261
body/bath-shower/dryness-dehydration                       242
hair/styling                                               235
skin/global-anti-aging/seruns                              221
health-care/nutrition                                      209
body/hands                                                 180
skin/moisturisers/oiliness-acne-pores                      177
skin/dehydration/seruns                                    173
skin/dark-spots/specific-moisturizers                      172
skin/cleansers-tonners/sensitive-skin                      169
skin/essences-preparing-lotions                            160
skin/eye-care/global-anti-aging                            159
mom-baby/first-years/hygiene-moisturization                156
sun-tan/face/normal-skin                                   153
skin/masks-exfoliators/exfoliating                         147
skin/loss-firmness/specific-moisturizers                   147
makeup/eyes-brows/mascara                                  138
skin/cleansers-tonners/dry-skin                            130
body/feet                                                  129
sun-tan/body/normal-skin                                   126
skin/lip-care/dryness-dehydration                          115
health-care/oral-health/toothbrushes-accessories           113
makeup/complexion/accessories-brushes                      111
health-care/veterinary-products                            111
skin/loss-firmness/seruns                                  109
mom-baby/first-years/feeding-accessories                   109
skin/oiliness-acne-pores/seruns                            108
skin/moisturisers/sensitive-intolerant-skin                105
hair/normal-hair/shampoo                                   103
body/female-intimate-hygiene                               102
body/sexuality                                             100
makeup/eyes-brows/eyeliners-pencil                          99
hair/dry-damaged-hair/shampoo                               99
fragrance/fragranced-moisturizers                           98
makeup/complexion/makeup-removers                           94
skin/masks-exfoliators/moisturizing-masks                   94
makeup/eyes-brows/eye-shadow                                91
sun-tan/self-tanning                                        91
men/hair/styling                                            90
makeup/complexion/foundation                                90
body/deodorants                                             90
hair/dry-damaged-hair/seruns-leave-in                       89
hair/hair-mask/dry-to-very-dry-hair                         88
makeup/complexion/concealers-highlighters                   87
makeup/eyes-brows/accessories-brushes                       85
skin/first-signs-age/specific-moisturizers                  85
sun-tan/face/combination-to-oily-skin                       79
skin/dark-spots/eye-contour                                 78
hair/colour/shampoo                                         77
makeup/complexion/primers                                   77
skin/eye-care/dryness-dehydration                           77
skin/moisturisers/redness-rosacea                           76
skin/masks-exfoliators/purifying-masks                      75
skin/beauty-tech                                            74
skin/deep-wrinkles/specific-moisturizers                    74
health-care/contact-lenses                                  71
makeup/lips/lipstick                                        71
body/exfoliators                                            70
makeup/eyes-brows/eyebrows                                  68
hair/contitioner/dry-to-very-dry-hair                       68
hair/hair-loss/seruns-leave-in                              68
supplements-vitamins/weight-management                      67
hair/brushes-combs                                          67
makeup/lips/lipgloss                                        65
supplements-vitamins/energy-tiredness                       65
makeup/complexion/powders                                   65
fragrance/bath                                              64
sun-tan/after-sun                                           64
health-care/tights-orthoses                                 64
skin/first-signs-age/seruns                                 63
sun-tan/face/lightness-anti-spots                           62
makeup/complexion/bb-creams-cc-creams                       60
supplements-vitamins/anti-ageing                            60
mom-baby/after-birth/breast-pumps                           59
hair/curly-hair/seruns-leave-in                             59
hair/accessories                                            58
hair/contitioner/normal-hair                                58
makeup/lips/lipbalm                                         58
sun-tan/face/sensitive-intolerant-skin                      58
health-care/oral-health/toothpaste                          58
skin/deep-wrinkles/seruns                                   55
mom-baby/sun-protection                                     54
skin/makeup-removers                                        54
hair/damaged-hair/masks                                     54
skin/eye-care/lost-firmness                                 53
skin/eye-care/first-wrinkles                                53
skin/seruns/redness-rosacea                                 53
health-care/oral-health/specific-care                       53
men/perfumes/deodorants                                     53
hair/colour/conditioners                                    52
hair/anti-dandruff/shampoo                                  51
hair/normal-hair/seruns-leave-in                            51
hair/shampoo/oily-hair                                      49
men/body/deodorants-antiperspirants                         49
skin/oiliness-acne-pores/targeted-correction                49
body/firming-care                                           48
health-care/first-aid                                       48
health-care/nasal-congestion                                48
men/shaving/shaving                                         48
skin/masks-exfoliators/anti-ageing                          47
hair/hair-loss/shampoo                                      46
hair/damaged-hair/seruns-leave-in                           46
men/shaving/after-shave                                     45
makeup/complexion/blush                                     45
supplements-vitamins/digestive-health                       44
hair/shampoo/volume                                         43
skin/facial-oils                                            43
body/scars-reparing-creams                                  42
hair/shampoo/sensitive-scalp                                42
makeup/nails/accessories-tools                              41
hair/seruns-leave-in                                        41
skin/cleansers-tonners                                      41
skin/masks-exfoliators/anti-spots-masks                     40
hair/damaged-hair/shampoo                                   40
men/body/hygiene-exfoliation                                40
makeup/eyes-brows/eye-makeup-removers                       40
skin/deep-wrinkles/eye-contour                              39
health-care/oral-health/mouthwashes                         39
makeup/nails/top-basecoats                                  39
makeup/complexion/bronzer                                   38
hair/damaged-hair/conditioners                              37
supplements-vitamins/hair-care                              37
health-care/dressings-anti-bedsore                          37
supplements-vitamins/vitamins-minerals                      36
hair/colour/masks                                           35
supplements-vitamins/sleep-anxiety                          35
body/atopic-dermatitis/bath-shower                          34
fragrance/deodorants                                        33
mom-baby/after-birth/breast-feeding                         33
skin/targeted-correction/oiliness-acne-pores                32
body/moisturisers/atopic-dermatitis                         32
men/shaving/styling                                         31
body/sculping                                               30
health-care/diapers-incontinence                            30
hair/preshampoo-head-scrub                                  29
makeup/lips/lipliners                                       29
supplements-vitamins/bones-joints                           29
sun-tan/eyes-lips-sensitive-areas                           29
men/sexuality/comdoms-lubricants                            28
men/perfumes/after-shave                                    28
mom-baby/first-years/diaper-change                          28
men/skin/cleansers-tonners                                  27
hair/shampoo-dry                                            26
hair/colour/color-protector                                 26
sun-tan/dark-spots                                          26
hair/colour/hair-dye                                        26
makeup/complexion/compact-foundation                        25
hair/contitioner/volume                                     25
hair/seruns-leave-in/volume                                 25
hair/hair-mask/normal-hair                                  25
supplements-vitamins/brain-memory                           24
health-care/bones-joints                                    24
health-care/insect-repellent                                24
makeup/nails/nail-polish                                    23
body/stretch-marks                                          23
skin/eyebrows-eyelashes                                     23
hair/seruns-leave-in/sensitive-scalp                        22
body/atopic-dermatitis/specific-care                        22
makeup/nails/treatments                                     22
hair/contitioner                                            22
mom-baby/first-years/fragrances                             22
sun-tan/face/dry-skin                                       22
sun-tan/body/sensitive-intolerant-skin                      22
health-care/tensiometers                                    22
skin/lip-care/wrinkles-fillers                              21
men/skin/anti-ageing                                        21
sun-tan/normal-skin/body                                    20
sun-tan/sensitivity/face                                    20
skin/neck-decollete-care                                    20
health-care/earplugs                                        19
hair/curly-hair/shampoo                                     19
health-care/scars-reparing-creams                           19
men/sexuality/accessories                                   19
supplements-vitamins/heart-circulation                      19
body/water-retention                                        19
mom-baby/maternity-essentials/maternity-bag                 18
mom-baby/first-years/atopic-skin                            18
men/skin/moisturisers/oily-skin                             18
hair/sun-care                                               18
health-care/oral-health/deep-cleansing                      18
hair/anti-ageing/shampoo                                    17
skin/dark-spots/essences-preparing-lotions                  16
men/hair/hair-loss                                          16
skin/eye-care/sensitive-intolerant-skin                     16
hair/curly-hair/conditioners                                16
body/cellulite-control                                      16
hair/contitioner/hair-loss                                  16
supplements-vitamins/bodybuilding                           16
men/hair/shampoos/normal-hair                               15
hair/curly-hair/masks                                       15
body/moisturisers                                           15
skin/global-anti-aging/essences-preparing-lotions           15
men/perfumes/bath                                           15
mom-baby/first-years/nasal-congestion                       15
mom-baby/first-years/soothers                               15
skin/oiliness-acne-pores/masks-exfoliators                  15
health-care/medication-boxes                                14
mom-baby/first-years/first-teeth                            14
mom-baby/after-birth/bras                                   14
supplements-vitamins/menopause                              14
hair/supplements                                            14
body/bust-care                                              14
sun-tan/normal-skin/face                                    14
hair/shampoo                                                14
skin/oiliness-acne-pores/essences-preparing-lotions         13
mom-baby/first-years                                        13
body/stubborn-fat                                           13
hair/seruns-leave-in/straightening                          12
men/skin/moisturisers/dry-skin                              12
mom-baby/maternity-essentials/strollers-accessories         12
mom-baby/before-birth/stretch-marks-firmness                11
men/body/moisturization-toning                              11
skin/dehydration/essences-preparing-lotions                 11
hair/anti-ageing/conditioners                               11
mom-baby/first-years/lices                                  11
hair/anti-ageing/seruns-leave-in                            11
supplements-vitamins/sun-care                               11
skin/dark-spots/targeted-correction                         11
sun-tan/supplements                                         11
skin/seruns                                                 10
hair/hair-loss/food-suplements                              10
health-care/anti-fungals                                    10
men/skin/seruns                                              9
men/hair/shampoos                                            9
body/bath-shower                                             9
sun-tan/hair                                                 8
men/skin/eye-care/dark-circles-puffiness                     8
hair/hair-loss/masks                                         8
supplements-vitamins/urinary-concerns                        8
sun-tan/pre-sun                                              8
hair/curly-hair                                              8
sun-tan/body                                                 8
men/hair/normal-hair                                         8
hair/anti-ageing/masks                                       8
hair/frizz-unruly-hair/seruns-leave-in                       8
health-care/nebulizers                                       8
makeup/nails/nail-polish-remover                             8
hair/colour                                                  7
men/skin/deep-wrinkles-loss-firmness                         7
body/moisturisers/psoriasis                                  7
skin/sensitive-intolerant-skin/cleansers-tonners             7
mom-baby/first-years/diapers                                 7
men/hair/shampoos/hair-loss                                  7
hair/hair-mask                                               7
skin/global-anti-aging                                       7
mom-baby/maternity-essentials/thermometers                   7
body/moisturisers/seborrheic-dermatitis                      7
hair/hair-mask/volume                                        7
sun-tan/oily-combination-skin                                7
skin/targeted-correction/lightness-anti-spots                7
supplements-vitamins/fertility                               6
men/shaving/accessories                                      6
health-care/menopause                                        6
skin/loss-firmness/essences-preparing-lotions                6
fragrance                                                    6
supplements-vitamins/nutrition                               6
hair/hair-mask/oily-hair                                     6
body/beauty-tech                                             6
hair/volume                                                  6
body/bath-shower/seborrheic-dermatitis                       6
sun-tan/sensitivity/body                                     6
mom-baby/first-years/cramps                                  5
hair/anti-dandruff/seruns-leave-in                           5
hair/sensitive-scalp                                         5
men/supplements/multivitamins                                5
men/skin/first-signs-age                                     5
men/skin/moisturisers/sensitive-skin                         5
skin/masks-exfoliators                                       5
health-care/diabetics                                        5
body/firmin-care                                             5
men/supplements/bodybuilding                                 5
body/psoriasis/specific-care                                 5
hair/hair-loss                                               5
mom-baby/first-years/cradle-cap                              5
hair/shampoo/straightening                                   5
skin/moisturisers                                            5
health-care/sleep-anxiety                                    4
men/skin/acne                                                4
hair/sensitive-scalp/preshampoo-head-scrub                   4
health-care/seborrheic-dermatitis/specific-care              4
men/supplements/fertility                                    4
hair/frizz-unruly-hair/shampoo                               4
men/skin/eye-care/wrinkles                                   4
body/bath-shower/psoriasis                                   4
sun-tan/dry-skin/face                                        4
hair/hair-mask/straightening                                 4
supplements-vitamins/eye-care                                4
body/hairs-removal                                           4
health-care/psoriasis/bath-shower                            4
hair/frizz-unruly-hair/conditioners                          4
sun-tan/body/dry-skin                                        4
skin/redness/masks-exfoliators                               3
skin/targeted-correction/deep-whrinkles                      3
hair/oily-hair/preshampoo-head-scrub                         3
supplements-vitamins/sexuality                               3
hair/contitioner/oily-hair                                   3
men/supplements/hair                                         3
men/skin/moisturisers                                        3
skin/hairs-removal                                           3
hair/dry-damaged-hair/styling                                3
mom-baby/before-birth/support-briefs-belts                   3
hair/damaged-hair/preshampoo-head-scrub                      3
hair/damaged-hair                                            3
hair/frizz-unruly-hair/masks                                 3
men/sexuality/food-supplements                               3
skin/eye-care                                                3
health-care/atopic-dermatitis/specific-care                  3
skin/deep-wrinkles/targeted-correction                       2
men/skin/beard-folliculitis                                  2

In [25]:
df_cleaned

,ref,itemDescriptionEN,brand,nameEN,encodeNameEN,title,description
0,000785FR,Combo Spot on 1 Pipette Dogs L 20-40 Kg,Frontline,Pet Care,health-care/veterinary-products,Combo Spot on Pipette Dogs 20-40 Kg,"The simple itching, caused by fleas can be a..."
1,000946DK,Men Eau de Toilette,DKNY,Fragrances,men/perfumes/fragrances,Men Eau de Toilette,"Discover DKNY Men Eau de Toilette — a modern, ..."
2,023444DK,Be Delicious Fresh Blossom Body Mist,DKNY,Fragrances,fragrance/women,Be Delicious Fresh Blossom Body Mist,DKNY Be Delicious Fresh Blossom Body Mist is a...
3,000784FR,Combo Spot on 1 Pipette Dogs M 10-20 Kg,Frontline,Pet Care,health-care/veterinary-products,Spot-On 10-20 Kg,"Have a dog as a companion is great, even bette..."
4,025034DK,Be Delicious Ice Pop Citrus Splash Eau de Parfum,DKNY,Fragrances,fragrance/women,Be Delicious Ice Pop Citrus Splash Eau de Parfum,DKNY Be Delicious Ice Pop Citrus Splash Eau de...
...,...,...,...,...,...,...,...
15985,025004G0,BB Cream 4-in-1 Treatment,Gamarde,BB Creams & CC Creams,makeup/complexion/bb-creams-cc-creams,BB Cream 4-in-1 Tinted Treatment,Discover Gamarde BB Cream 4-in-1 Tinted Treatm...
15986,024555UF,Curcuma Plus Food Supplement,Vitafor,Nutrition & Food Supplements,health-care/nutrition,Curcuma Plus Food Supplement Capsules,Boost immunity and fight oxidative stress with...
15987,024558UF,Endurance Caffeine Gel Food Supplement,Vitafor,Nutrition & Food Supplements,health-care/nutrition,Endurance Caffeine Gel Carbohydrate Food Suppl...,Vitafor Endurance Caffeine Gel Carbohydrate Fo...
15988,024571UF,Lipix 6 Safflower and Grape Seed Oil Food Supp...,Vitafor,Nutrition & Food Supplements,health-care/nutrition,Lipix 6 Safflower and Grape Seed Oil Food Supp...,Boost workouts and metabolism with Vitafor Lip...
15989,024837B6,Shine Brown Chocolate Quick Tanning Cream,Byrokko,Self-Tanning,sun-tan/self-tanning,Shine Brown Chocolate Quick Tanning Cream for ...,"Achieve an intense, deep chocolate tan with By..."

In [26]:
df_cleaned.to_csv('product_info_01.csv', index=False)